---
name: 'Destroy Heroku Application'
description: 'Destroys a given Heroku Application with a given name.'

inputs:
  heroku_api_key:
    description: 'API key with the needed permissions'
    required: true
  app_name:
    description: 'Application name to destroy'
    required: true
outputs:
  success:
    description: "true/false if the app was found and deleted"
    value: ${{ steps.destroy.outputs.exists }}

runs:
  using: "composite"
  steps:
    - name: destroying heroku application
      id: destroy
      shell: bash
      env:
        HEROKU_API_KEY: ${{ inputs.heroku_api_key }}
      run: "
        if heroku info --app '${{ inputs.app_name }}'; then
          echo ::set-output name=exists::true ;
          heroku apps:destroy --app '${{ inputs.app_name }}' --confirm '${{ inputs.app_name }}'
        else
          echo ::set-output name=exists::false
        fi
      "
